FROM php:8.5-apache

RUN a2enmod headers rewrite

# Install system dependencies 
RUN apt-get update && apt-get install -y \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install and enable PostgreSQL extensions 
RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pgsql pdo_pgsql